// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Vite exposes environment variables through import.meta.env
// Variables must be prefixed with VITE_ to be accessible in client-side code
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

console.log("Supabase Config:", {
  url: SUPABASE_URL,
  hasKey: !!SUPABASE_ANON_KEY,
  keyPrefix: SUPABASE_ANON_KEY?.substring(0, 20) + "..."
});

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error("Missing Supabase environment variables:", {
    hasUrl: !!SUPABASE_URL,
    hasKey: !!SUPABASE_ANON_KEY
  });
  throw new Error("Supabase environment variables are not configured. Please check your .env.local file.");
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);